import type { Metadata } from "next";

import "./globals.css";

import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/ThemeProvider";
import MarketData from "@/components/MarketData";

import StoreProvider from "@/components/StoreProvider";
import MobileMenu from "@/components/MobileMenu";
import { Toaster } from "sonner";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <StoreProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="flex flex-col sm:order-1 gap-3">
              <div className="order-2">
                <MarketData />
              </div>
              <div className="sm:hidden order-1 sm:order-2">
                <Navbar />
              </div>
            </div>

            <main className=" max-w-[80%] mx-auto mt-6 ">
              {" "}
              <div className="hidden sm:block">
                <Navbar />
              </div>
              {children}
              <Toaster
                richColors
                position="bottom-right"
                toastOptions={{
                  classNames: {
                    toast:
                      "bg-white dark:bg-[#1f1f2e] text-sm shadow-lg rounded-lg px-4 py-3",
                    title: "font-bold text-black dark:text-white",
                    description: "text-gray-500 dark:text-gray-400",
                    actionButton:
                      "bg-main-purple text-white px-2 py-1 rounded-md",
                    cancelButton: "text-red-500",
                  },
                }}
              />
            </main>
            <MobileMenu />
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
